version: '3'
services:
  image_server_1:
    image: 'imageserver-v1'
    build:
      context: .
      dockerfile: dockerfile   
    restart: always
    expose:
      - "80"
      - "443"  
    ports:
      - "8086:80"
    volumes:
      - /qin/SiteLogs/Image.Server/8086:/app/logs
    logging:
      options:
        max-size: 50m
  image_server_2:
    image: 'imageserver-v1'
    build:
      context: .
      dockerfile: dockerfile   
    restart: always
    expose:
      - "80"
      - "443"  
    ports:
      - "8087:80"
    volumes:
      - /qin/SiteLogs/Image.Server/8087:/app/logs
    logging:
      options:
        max-size: 50m
  image_server_3:
    image: 'imageserver-v1'
    build:
      context: .
      dockerfile: dockerfile   
    restart: always
    expose:
      - "80"
      - "443"  
    ports:
      - "8088:80"
    volumes:
      - /qin/SiteLogs/Image.Server/8088:/app/logs
    logging:
      options:
        max-size: 50m
